---
# task to start petclinic_app
- name: Add "petclinic" user
  ansible.builtin.user: 
    name: petclinic
    shell: /usr/bin/false
    system: yes

- name: Create petclinic dir and chown it
  ansible.builtin.file: 
    path: /opt/petclinic
    state: directory
    recurse: yes
    owner: petclinic
    group: petclinic

- name: Command performs "cd" command & copies artifact from cloud bucket to controlled machine
  ansible.builtin.shell: 
    cmd: gsutil cp gs://petclinic-artifacts-krutseniuk/csr/target/spring-petclinic-2.7.3.jar {{jar_file_name}}
  #for some reason, firstly comes cp command and chdir afterwards, though actually chdir is performed first and cmd
  #is performed after chdir 
    chdir: /opt/petclinic    

- name: Change copied artifact's ownership&group
  ansible.builtin.file: 
    path: /opt/petclinic/{{jar_file_name}} #or /opt/petclinic-gcplab-bucket.jar
    owner: petclinic
    group: petclinic

- name: Put template file in systemd folder and make it systemd-service
  ansible.builtin.template: 
    src: petclinic.service.j2
    dest: /etc/systemd/system/petclinic.service
  notify: Daemon_reload      